import './globals.css'
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import localFont from "next/font/local";
import CssBaseline from '@mui/material/CssBaseline';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import AppTheme from "@components/templates/app-theme";
import StoreProvider from "@/components/providers/store-provider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <StoreProvider>
                    <InitColorSchemeScript attribute="class" />
                    <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                        <AppTheme>
                            <CssBaseline enableColorScheme />
                            {children}
                        </AppTheme>
                    </AppRouterCacheProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
